DROP USER api_test CASCADE;

CREATE USER api_test IDENTIFIED BY api_test DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP;

ALTER USER api_test QUOTA 100M ON USERS;
GRANT CONNECT TO api_test;
GRANT CREATE TABLE TO api_test;
GRANT CREATE VIEW TO api_test;
GRANT CREATE SEQUENCE TO api_test;
GRANT CREATE TRIGGER TO api_test;
GRANT CREATE SYNONYM TO api_test;
GRANT CREATE PROCEDURE TO api_test;
GRANT CREATE TYPE TO api_test;
GRANT SELECT_CATALOG_ROLE TO api_test;
GRANT EXECUTE_CATALOG_ROLE TO api_test;

exit;
